stages:
    - build
    - test

before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -qq libboost-all-dev python3 python3-dev python3-pip python3-tk
    - pip3 install -r requirements_dev.txt



build:
    stage: build
    script:
    - python3 setup.py build_ext --inplace


test:
    stage: test
    script:
    - python3 setup.py install
    - tox
    dependencies:
    - build
