build:
    script:
    - apt-get update -qq && apt-get install -qq libboost-all-dev python3 python3-dev python3-pip python3-tk
    - pip3 install --upgrade pip
    - pip3 install scipy numpy matplotlib urllib3 cython pytest matplotlib
    - python3 setup.py build_ext --inplace
    - pytest
