
# Config file for automatic testing at travis-ci.org

dist: bionic
language: python
python:
  - 3.7
  - 3.8

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -U tox-travis
script:
    - tox

# Deploy to PyPI on tags
deploy:
  provider: pypi
  username: __token__
  password:
    secure: murgTLV9a+VGIr2z0SEoOGycGey1GIgf1dFcY7//0+IOGL4mfN7QFXPwBUhE7uPZebfwHqYTNLJCVEEi4FF3KQniOAFhACKizK+30jMbGpLPWxfGGbCzjEpMD84XHvqipa1XWVm3K3g51ekHscy6fh8ZXhWe6yWFlVT2DzvTv8q54IErKwvUT00Bi/xaqr4Cb6edbKzKvEB+fpGL3w3S2ZKn+X8YINT6DwJPs2FC3pBQ3OArJCTcxtnrTsg5Za60W68Uludjy3DRc8mIjTM0deXRBgMpbygvNdNbDgiFYoSucR8ThBcxyLVGu8pcowwHl3x20pzbln5ZdXezBKu93vK7Zd7aCWH+B05EhIP2O2xBMtf1PhNSBsheRrQ4UAatxKsZX+Zcgnk1oYpDyvkuKvdxbeMTqkGgAk8KhfkwSMfKURRL21F3iZj5VlUVHekNLTdfeMNK4Pn4lgguAGku/EBIHPJOIeN5+0SQvqlRWhYnwZ+GLVyLv/0lMN3RnQnUeU/7KdrEsKalIeTRnV0bN0eXpzZCvRLJvJdPvjXi9aBqAei/jWtdzJOOJ/kUsxYLzJnEhs0vTv6HtXgliZgDrdmocemkql7GfFuohXEO12gvUZId0NgiSaj7z1TZehKqkRdMHzusudX+lVjBlvabCzOz78wgITrJuZB4oGid5EQ=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
